package io.juicebreak.prompt

import kotlin.random.Random

fun randomNoun(): String =
    nouns[Random.nextInt(0, nouns.size)]

fun randomAdjective(): String =
    adjectives[Random.nextInt(0, adjectives.size)]

fun randomFighter(): String =
    fighters[Random.nextInt(0, fighters.size)]

fun randomPower(): String =
    powers[Random.nextInt(0, powers.size)]

fun randomBuzzword(): String =
    buzzwords[Random.nextInt(0, buzzwords.size)]

val nouns: List<String> = listOf(
    "squirrel",
    "bunny",
    "farmer",
    "umbrella",
    "train",
    "mayor",
    "alpaca",
    "lumberjack",
    "engineer",
    "bathtub",
    "bear",
    "anteater",
    "turtle",
    "lizard",
    "geco",
    "taco",
    "mummy",
    "werewolf",
    "cloud",
    "puppy",
    "dog",
    "cat",
    "kitten",
    "snake",
    "chicken",
    "turkey",
    "flower",
    "dinosaur",
    "alligator",
    "spider",
    "goose",
    "duck",
    "antelope",
    "kangaroo",
    "cookie",
    "cheese",
    "toaster",
    "sandwich",
    "coffee pot",
    "lamp",
    "deer",
    "dragon",
    "pangolin",
    "ninja",
    "pirate",
    "police officer",
    "tiger",
    "lion",
    "car",
    "bicycle",
    "iguana",
    "laptop",
    "book",
    "lightbulb",
    "refrigerator",
    "microwave",
    "chameleon",
    "toothbrush",
    "floss",
    "elf",
    "dwarf",
    "knight",
    "wizard",
    "broccoli",
    "orange",
    "muffin",
    "bee",
    "donut",
    "cow",
    "dolphin",
    "pig",
    "owl",
    "dog",
    "elephant",
    "tree",
    "crab",
    "apple",
    "Walrus",
    "Meerkat",
    "Waffle",
    "Car",
    "Bicycle",
    "Clown",
    "Shark"
)

val adjectives: List<String> = listOf(
    " bearded",
    " beautiful",
    " bossy",
    " brave",
    " burly",
    " charming",
    " chill",
    " clever",
    " confident",
    " consoling",
    " courageous",
    " cowardly",
    " crabby",
    " crazy",
    " creative",
    " creepy",
    " curly",
    " cute",
    " devious",
    " diplomatic",
    " disreputable",
    " dreamy",
    " fearful",
    " friendly",
    " frozen",
    " funny",
    " greedy",
    " grumpy",
    " hard-working",
    " lazy",
    " magical",
    " mischevious",
    " misunderstood",
    " mysterious",
    " nervous",
    " nosey",
    " philosophical",
    " rebellious",
    " relaxed",
    " respectful",
    " self-disciplined",
    " shiny",
    " sinister",
    " sleepy",
    " smart",
    " sneaky",
    " social",
    " sophisticated",
    " spooky",
    " studious",
    " supersticious",
    " surprised",
    " sweet",
    " tough",
    " vain",
    " wise",
    "n absent-minded",
    "n ambitious",
    "n angry",
    "n angry",
    "n anxious",
    "n approachable",
    "n embarassed",
    "n enthusiastic",
    "n exceptional",
    "n impractical",
    "n indiscrete",
    "n itchy",
    "n objectionable",
    "n ugly"
)

val fighters: List<String> = listOf(
    "a bear",
    "a pirate",
    "a mummy",
    "a vampire",
    "a ninja",
    "a shark",
    "Bruce Lee",
    "a T. Rex",
    "a Raptor",
    "Wolverine",
    "Captain America",
    "Batman",
    "Thor",
    "Spider-Man",
    "Wonder Woman",
    "a wolverine",
    "The Hulk",
    "a viking",
    "a whale",
    "a rhinoceros",
    "a dolphin",
    "a walrus",
    "a wizard",
    "a knight",
    "a dwarf",
    "a tiger",
    "a lion",
    "a dragon",
    "a kangaroo",
    "Optimus Prime",
    "Superman",
    "Rambo",
    "Mike Tyson",
    "Peter Pan",
    "a zombie",
    "a pair of kids in a trenchcoat",
    "a giant squid",
    "a raccoon",
    "Hurcules",
    "Zeus",
    "a cheetah",
    "a gorilla",
    "a witch",
    "Sasquatch",
    "a cyclops",
    "An army of meerkats",
    "Snow White's Seven Dwarves",
    "Katniss Everdeen",
    "Darth Vader",
    "The Loch Ness Monster",
    "Santa Claus"
)

val powers: List<String> = listOf(
    "with a chainsaw",
    "with lasers",
    "with telepathy",
    "with a sword",
    "with a lightsaber",
    "with Thor's Hammer",
    "with Captain America's Shield",
    "with Batarangs",
    "with Wolverine's Claws",
    "with a bazooka",
    "riding a war elephant",
    "in a space suit",
    "with a flamethrower",
    "wearing a jetpack",
    "on a hoverboard",
    "with the ability to fly",
    "with the ability to control metal",
    "carryiing a trident",
    "with the ability to shrink",
    "with the ability to grow",
    "with x-ray vision",
    "with laser vision",
    "with the ability to turn invisible",
    "leading a small army of chickens",
    "wearing a suit of armor",
    "with the ability to teleport",
    "with cannons instead of hands",
    "driving a tank",
    "driving a car",
    "flying a plane",
    "wearing sunglasses",
    "with a grappling hook",
    "who sneezes spiders",
    "carrying dynamite",
    "with a slingshot",
    "with a mace",
    "with an axe",
    "with a lighter",
    "with super speed",
    "with a tennis racket",
    "wearing an invisibility cloak",
    "with a magic wand",
    "who spits acid",
    "in a mech suit",
    "armed with technology from the year 2400"
)

val buzzwords: List<String> = listOf(
    "Orange",
    "Apple",
    "Banana",
    "Squash",
    "Cookie",
    "Muffin",
    "Toast",
    "Bagel",
    "Sandwich",
    "Peanut Butter",
    "Jelly",
    "Waffle",
    "Pancake",
    "Chair",
    "Couch",
    "Television",
    "Night Stand",
    "Table",
    "Lamp",
    "Laptop",
    "Computer",
    "Keyboard",
    "Mouse",
    "Monitor",
    "Cup",
    "Pencil",
    "Eraser",
    "Hilighter",
    "Orangutang",
    "Monkey",
    "Gorilla",
    "Meerkat",
    "Penguin",
    "Lizard",
    "Horse",
    "Puppy",
    "Kitten",
    "Cat",
    "Dog",
    "Toaster",
    "Stove",
    "Dishwasher",
    "Sink",
    "Microwave",
    "Freezer",
    "Washing Machine",
    "Jukebox",
    "Radio",
    "Bluetooth",
    "WiFi",
    "Wireless Charging"
)
