package io.juicebreak.prompt

val nouns: List<String> = listOf(
    "squirrel",
    "bunny",
    "farmer",
    "umbrella",
    "train",
    "mayor",
    "alpaca",
    "lumberjack",
    "engineer",
    "bathtub",
    "bear",
    "anteater",
    "turtle",
    "lizard",
    "geco",
    "taco",
    "mummy",
    "werewolf",
    "cloud",
    "puppy",
    "dog",
    "cat",
    "kitten",
    "snake",
    "chicken",
    "turkey",
    "flower",
    "dinosaur",
    "alligator",
    "spider",
    "goose",
    "duck",
    "antelope",
    "kangaroo",
    "cookie",
    "cheese",
    "toaster",
    "sandwich",
    "coffee pot",
    "lamp",
    "deer",
    "dragon",
    "pangolin",
    "ninja",
    "pirate",
    "police officer",
    "tiger",
    "lion",
    "car",
    "bicycle",
    "iguana",
    "laptop",
    "book",
    "lightbulb",
    "refrigerator",
    "microwave",
    "chameleon",
    "toothbrush",
    "floss",
    "elf",
    "dwarf",
    "knight",
    "wizard",
    "broccoli",
    "orange",
    "muffin",
    "bee",
    "donut",
    "cow",
    "dolphin",
    "pig",
    "owl",
    "dog",
    "elephant",
    "tree",
    "crab",
    "apple",
    "Walrus",
    "Meerkat",
    "Waffle",
    "Car",
    "Bicycle",
    "Clown",
    "Shark"
)

val adjectives: List<String> = listOf(
    " bearded",
    " beautiful",
    " bossy",
    " brave",
    " burly",
    " charming",
    " chill",
    " clever",
    " confident",
    " consoling",
    " courageous",
    " cowardly",
    " crabby",
    " crazy",
    " creative",
    " creepy",
    " curly",
    " cute",
    " devious",
    " diplomatic",
    " disreputable",
    " dreamy",
    " fearful",
    " friendly",
    " frozen",
    " funny",
    " greedy",
    " grumpy",
    " hard-working",
    " lazy",
    " magical",
    " mischevious",
    " misunderstood",
    " mysterious",
    " nervous",
    " nosey",
    " philosophical",
    " rebellious",
    " relaxed",
    " respectful",
    " self-disciplined",
    " shiny",
    " sinister",
    " sleepy",
    " smart",
    " sneaky",
    " social",
    " sophisticated",
    " spooky",
    " studious",
    " supersticious",
    " surprised",
    " sweet",
    " tough",
    " vain",
    " wise",
    "n absent-minded",
    "n ambitious",
    "n angry",
    "n angry",
    "n anxious",
    "n approachable",
    "n embarassed",
    "n enthusiastic",
    "n exceptional",
    "n impractical",
    "n indiscrete",
    "n itchy",
    "n objectionable",
    "n ugly"
)

val fighters: List<String> = listOf(
    "a bear",
    "a pirate",
    "a mummy",
    "a vampire",
    "a ninja",
    "a shark",
    "Bruce Lee",
    "a T. Rex",
    "a Raptor",
    "Wolverine",
    "Captain America",
    "Batman",
    "Thor",
    "Spider-Man",
    "Wonder Woman",
    "a wolverine",
    "The Hulk",
    "a viking",
    "a whale",
    "a rhinoceros",
    "a dolphin",
    "a walrus",
    "a wizard",
    "a knight",
    "a dwarf",
    "a tiger",
    "a lion",
    "a dragon",
    "a kangaroo",
    "Optimus Prime",
    "Superman",
    "Rambo",
    "Mike Tyson",
    "Peter Pan",
    "a zombie",
    "a pair of kids in a trenchcoat",
    "a giant squid",
    "a raccoon",
    "Hurcules",
    "Zeus",
    "a cheetah",
    "a gorilla",
    "a witch",
    "Sasquatch",
    "a cyclops",
    "An army of meerkats",
    "Snow White's Seven Dwarves",
    "Katniss Everdeen",
    "Darth Vader",
    "The Loch Ness Monster",
    "Santa Claus"
)

val powers: List<String> = listOf(
    "with a chainsaw",
    "with lasers",
    "with telepathy",
    "with a sword",
    "with a lightsaber",
    "with Thor's Hammer",
    "with Captain America's Shield",
    "with Batarangs",
    "with Wolverine's Claws",
    "with a bazooka",
    "riding a war elephant",
    "in a space suit",
    "with a flamethrower",
    "wearing a jetpack",
    "on a hoverboard",
    "with the ability to fly",
    "with the ability to control metal",
    "carryiing a trident",
    "with the ability to shrink",
    "with the ability to grow",
    "with x-ray vision",
    "with laser vision",
    "with the ability to turn invisible",
    "leading a small army of chickens",
    "wearing a suit of armor",
    "with the ability to teleport",
    "with cannons instead of hands",
    "driving a tank",
    "driving a car",
    "flying a plane",
    "wearing sunglasses",
    "with a grappling hook",
    "who sneezes spiders",
    "carrying dynamite",
    "with a slingshot",
    "with a mace",
    "with an axe",
    "with a lighter",
    "with super speed",
    "with a tennis racket",
    "wearing an invisibility cloak",
    "with a magic wand",
    "who spits acid",
    "in a mech suit",
    "armed with technology from the year 2400"
)

val buzzwords: List<String> = listOf(
    "Orange",
    "Apple",
    "Banana",
    "Squash",
    "Cookie",
    "Muffin",
    "Toast",
    "Bagel",
    "Sandwich",
    "Peanut Butter",
    "Jelly",
    "Waffle",
    "Pancake",
    "Chair",
    "Couch",
    "Television",
    "Night Stand",
    "Table",
    "Lamp",
    "Laptop",
    "Computer",
    "Keyboard",
    "Mouse",
    "Monitor",
    "Cup",
    "Pencil",
    "Eraser",
    "Hilighter",
    "Orangutang",
    "Monkey",
    "Gorilla",
    "Meerkat",
    "Penguin",
    "Lizard",
    "Horse",
    "Puppy",
    "Kitten",
    "Cat",
    "Dog",
    "Toaster",
    "Stove",
    "Dishwasher",
    "Sink",
    "Microwave",
    "Freezer",
    "Washing Machine",
    "Jukebox",
    "Radio",
    "Bluetooth",
    "WiFi",
    "Wireless Charging"
)

val debates: List<String> = listOf(
    "Is a poptart a raviolli?",
    "Is a taco a sandwich?",
    "Would you rather fight a single horse-sized chicken or one hundred chicken-sized horses?",
    "At what scale is a cookie really a cake?",
    "Is a bike carrying a third wheel a tricycle?",
    "Is transparent a color?",
    "Does the lorax speak for other plants?",
    "Can a bar of soap ever get dirty?",
    "Is water wet?",
    "Is a calzone a pastry?",
    "Is spaghetti a salad?",
    "If a naughty child asks Santa for coal, will they get it?"
)

val events: List<String> = listOf(
    "You suddenly have the power to convert coal into spagetthi.",
    "You can suddenly tell how much something weighs by licking it.",
    "The sky has turned yellow except for one square meter directly above your house.",
    "All fish in North America has been converted into Sweedish Fish.",
    "You suddenly know every time someone in your immediate vicinity has said the word \"Pineapple\".",
    "You can make someone unallergic to something at the cost of their being extremely allergic to their favorite food.",
    "You are suddenly able to control one cubic centimeter of gas with your mind.",
    "Antartica has suddenly moved to the center of the Pacific ocean.",
    "You find yourself in possession of all typewriters in England."
)

val words: Map<String, List<String>> = mapOf(
    "noun" to nouns,
    "adjective" to adjectives,
    "fighter" to fighters,
    "power" to powers,
    "buzzword" to buzzwords,
    "debate" to debates,
    "event" to events
)
